# THIS FILE WAS AUTOGENERATED, DO NOT EDIT
abort 'Use the rake task or esr-gem-builder to build the gem' if $0 =~ /gem$/ && $*.first == 'build'
Gem::Specification.new do |s|
  s.name = "rgen"
  s.version = "0.8.3"
  s.authors = ["Martin Thiede"]
  s.homepage = "http://ruby-gen.org"
  s.summary = "Ruby Modelling and Generator Framework"
  s.description = "RGen is a framework for Model Driven Software Development (MDSD) in Ruby. This means that it helps you build Metamodels, instantiate Models, modify and transform Models and finally generate arbitrary textual content from it."
  s.licenses = nil
  s.bindir = "bin"
  s.executables = nil
  s.extra_rdoc_files = ["README.rdoc", "CHANGELOG", "MIT-LICENSE"]
  s.rdoc_options << "--main" << "README.rdoc" << "-x" << "test" << "-x" << "metamodels" << "-x" << "ea_support/uml13*"
  s.files = ["README.rdoc", "CHANGELOG", "MIT-LICENSE", "Rakefile", "Project.yaml"] + Dir.glob("lib/**/*") + Dir.glob("test/**/*") + Dir.glob("lib/**/*.rb") + ["lib/rubyencoder.lic"] - Dir.glob("**/*.bak")
  s.add_development_dependency("nokogiri", "~> 1.6", ">= 1.6.8.1")
  s.add_development_dependency("rake", "~> 12.0")
  s.add_development_dependency("minitest", "~> 5.10", ">= 5.10.1")
  s.add_development_dependency("minitest-fail-fast", "~> 0.1.0")
end
