
# THIS FILE WAS AUTOGENERATED, DO NOT EDIT
require 'yaml'

Class.new do

def initialize
  @project_path = File.dirname(__FILE__)
  @project_config_path = File.join(File.dirname(__FILE__), 'Project.yaml')
  @project_config = YAML.load(File.read(@project_config_path))
end

def rubies
  (@project_config['rubies'] || ['2.3']).map(&:to_s)
end

def platform_rubies
  @project_config['platform_rubies'] || {}
end

# Ruby versions to package for a declared platform: its platform_rubies override, else the
# global rubies. Keyed by the declared platform string (pre patch_platform).
def rubies_for_platform(platform)
  (platform_rubies[platform.to_s] || rubies).map(&:to_s)
end

def platforms
  @project_config['platforms'] || %w(x86_64-linux x64-mingw32)
end

def exclude_files
  @project_config['exclude_files'] || []
end

def encrypt_sources
  @project_config['encrypt_sources'].nil? ? true : @project_config['encrypt_sources']
end

def extensions
  @project_config['extensions'] ||
      Hash[Dir.glob(File.join(@project_path, 'ext', '*')).select { |f| File.directory?(f) }.map { |f| [File.basename(f).to_sym, f] }]
end

def common_native_binary_paths
  @project_config['common_native_binary_paths']
end

def native_library_artifacts
  @project_config['native_library_artifacts']
end

def common_native_binary_artifacts
  @project_config['common_native_binary_artifacts'] || {}
end

def extensions_target_path
  @project_config['extensions_target_path'] || File.join('lib', 'native')
end

# All extension artifact path list. Iterates each declared platform with its own Ruby set
# (rubies_for_platform), so a platform can ship a subset of the global rubies.
def native_library_artifact_paths(only_platforms = nil)
  platforms_list = only_platforms.nil? ? platforms : only_platforms
  extensions.keys.flat_map do |name|
    platforms_list.flat_map do |platform|
      rubies_for_platform(platform).flat_map do |ruby|
        slot = patch_platform(ruby, platform)
        if native_library_artifacts && native_library_artifacts[name.to_s]
          native_library_artifacts[name.to_s].map do |artifact_platform, artifacts|
            next unless slot == artifact_platform.to_s
            artifacts.map { |a| File.join(extensions_target_path, name.to_s, ruby, slot, a) }
          end
        elsif @project_config['native_artifacts'] && @project_config['native_artifacts'][name.to_s] # backward compatibility (e.g. esr-licensing <0.3)
          @project_config['native_artifacts'][name.to_s].map do |artifact|
            next unless slot == slot.to_s
            File.join(extensions_target_path, name.to_s, ruby.to_s, slot, artifact)
          end
        else
          [File.join(extensions_target_path, name.to_s, ruby.to_s, slot, name.to_s + '.so')]
        end
      end
    end
  end
end

def common_native_binary_path(name, platform = nil)
  path = common_native_binary_paths[name] unless common_native_binary_paths.nil?
  path = path[platform || RUBY_PLATFORM] if path.is_a?(Hash)
  path || File.join('native', name)
end

def patch_platform(ruby, platform)
  # `-gnu` triples are glibc aliases of the canonical Linux slots; collapse them so
  # packaging looks in the non-`-gnu` directory where the binaries were placed.
  platform = 'x86_64-linux' if platform == 'x86_64-linux-gnu'
  platform = 'aarch64-linux' if platform == 'aarch64-linux-gnu'
  if platform == 'x64-mingw32' && !['1.9', '2.0', '2.1', '2.2', '2.3', '2.4', '2.5', '2.6', '2.7', '3.0'].include?(ruby)
    'x64-mingw-ucrt' # RubyInstaller uses this one with Ruby 3.1+
  elsif platform == 'x64-mingw-ucrt' && ['1.9', '2.0', '2.1', '2.2', '2.3', '2.4', '2.5', '2.6', '2.7', '3.0'].include?(ruby)
    'x64-mingw32'
  else
    platform
  end
end

def common_native_binary_artifact_paths(only_platforms = nil)
  common_native_binary_artifacts.flat_map do |name, info|
    info.flat_map do |platform, binaries|
      platform = patch_platform(ruby, platform)
      next if only_platforms && !only_platforms.include?(platform.to_s)
      binaries.map { |binary| File.join(common_native_binary_path(name, platform), binary) }
    end
  end.compact
end

def native_artifact_paths(only_platforms = nil)
  native_library_artifact_paths(only_platforms) + common_native_binary_artifact_paths(only_platforms)
end

def gemspec
  Gem::Specification.new do |s|
    s.name = @project_config['name']
    s.version = @project_config['version']
    s.authors = @project_config['authors']
    s.homepage = @project_config['homepage']
    s.summary = @project_config['summary']
    s.description = @project_config['description']
    s.licenses = @project_config['licenses']
    s.bindir = @project_config['bindir'] || 'bin'
    s.executables = @project_config['executables']
    s.extra_rdoc_files = @project_config['extra_rdoc_files']
    s.rdoc_options.push(*@project_config['rdoc_options']) if @project_config['rdoc_options']
    include_patterns = (@project_config['include_files'] || []) + ["lib/**/*.rb", "Project.yaml"]
    include = include_patterns.reject { |i| i.include?('*') } +
        include_patterns.select { |i| i.include?('*') }.flat_map { |i| Dir.glob(i) }
    # Native extension artifacts are contributed here (never via include_files globs), so the set
    # can be tailored per gem. $blt_target_platform (a command-line argument passed by
    # `blt build-gem` in platform-fat mode) restricts this gem to a single platform: mark it with
    # s.platform and add only that platform's binaries. When unset, add every declared platform's
    # binaries into one universal gem (historical default).
    target_platform = defined?($blt_target_platform) ? $blt_target_platform : nil
    if target_platform && !target_platform.empty?
      s.platform = target_platform
      # Select artifacts by their actual on-disk slot (the platform directory the binary lives in),
      # not by the declared platform: patch_platform rewrites x64-mingw32<->x64-mingw-ucrt per Ruby,
      # so a single gem's platform must match RUBY_PLATFORM exactly. The slot is the parent dir of
      # each native-library artifact. Common native binaries are already platform-filtered by path.
      slot = ->(p) { File.basename(File.dirname(p)) }
      include.concat(native_library_artifact_paths.select { |p| slot.call(p) == target_platform })
      include.concat(common_native_binary_artifact_paths([target_platform]))
    else
      include.concat(native_artifact_paths)
    end
    include << "lib/rubyencoder.lic" if encrypt_sources and encrypt_sources == "rubyencoder"
    exclude_files_expanded = exclude_files.reject { |i| i.include?('*') }
    exclude = exclude_files_expanded +
        exclude_files.select { |i| i.include?('*') }.flat_map { |i| Dir.glob(i) }
    s.files = include - exclude 
    (@project_config['dependencies'] || {}).flat_map do |_, deps|
      deps.map do |d|
        if d.is_a?(String)
          s.add_dependency(d)
        else
          dep_args = [d['name']]
          dep_args.concat(if d['version'].nil?; []; else d['version'].is_a?(String) ? [d['version']] : d['version'] end)
          if d['development']
            s.add_development_dependency(*dep_args)
          else
            s.add_dependency(*dep_args)
          end
        end
      end
    end
  end
end

end.new.gemspec
    